name: Remove Custom Domain

on:
  workflow_dispatch:

jobs:
  remove-custom-domain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Remove custom domain
        run: |
          # Create a JSON payload to update repository settings
          echo '{"has_pages":true,"source":{"branch":"main","path":"/"}}' > pages_config.json
          
          # Make GitHub API request to update settings (remove custom domain)
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d @pages_config.json \
            "https://api.github.com/repos/${{ github.repository }}/pages" 